version: '3'

services:
  php-fpm:
    container_name: php-fpm
    build:
      context: data/docker
      dockerfile: dev/php-fpm/Dockerfile
    working_dir: /app
    environment:
      APP_DOCKER: 1
    volumes:
      - ./:/app
  php-cli:
    container_name: php-cli
    build:
      context: data/docker
      dockerfile: dev/php-cli/Dockerfile
    working_dir: /app
    environment:
      APP_DOCKER: 1
    volumes:
      - ./:/app
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: education
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 54321:5432
  postgres-test:
    container_name: postgres-test
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: education_test
    volumes:
      - postgres-test:/var/lib/postgresql/data
    ports:
      - 54322:5432
  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
      - 11211:11211
    volumes:
      - ./:/app
    restart: always
  nginx:
    container_name: nginx
    build:
      context: data/docker
      dockerfile: dev/nginx/Dockerfile
    ports:
      - 8080:80
    volumes:
      - ./:/app
    depends_on:
      - php-fpm
    restart: always

volumes:
  postgres:
  postgres-test:
